apiVersion: v1
kind: Service
metadata:
  name: {{ template "proxy-relay.fullname" . }}
  labels:
{{ include "proxy-relay.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "proxy-relay.name" . }}
    release: {{ .Release.Name }}
