hpa:
  minReplicas: 2
  maxReplicas: 4
  cpuMax: 80
  memoryMax: 70

podDisruptionBudget:
  minAvailable: 1

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 300
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
